export const ORDER_ACTION_TYPES = {
  ADD_ORDER_START: "order/ADD_ORDER_START",
  ADD_ORDER_SUCCESS: "order/ADD_ORDER_SUCCESS",
  ADD_ORDER_FAILED: "order/ADD_ORDER_FAILED",

  FETCH_ORDERS_START: "/FETCH_ORDERS_START",
  FETCH_ORDERS_SUCCESS: "/FETCH_ORDERS_SUCCESS",
  FETCH_ORDERS_FAILED: "/FETCH_ORDERS_FAILED",
};

export const ORDER_STATUS_TYPES = {
  PENDING: "pending",
  COMPLETED: "completed",
  REJECTED: "rejected",
  CONFIRMED: "confirmed",
};
