export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: "category/FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "category/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "category/FETCH_CATEGORIES_FAILED",

  ADD_PRODUCT_START: "category/ADD_PRODUCT_START",
  ADD_PRODUCT_SUCCESS: "category/ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILED: "category/ADD_PRODUCT_FAILED",

  REMOVE_PRODUCT_START: "category/REMOVE_PRODUCT_START",
  REMOVE_PRODUCT_SUCCESS: "category/REMOVE_PRODUCT_SUCCESS",
  REMOVE_PRODUCT_FAILED: "category/REMOVE_PRODUCT_FAILED",
};
